stages:
  - install
  - build
  - quality
  - deploy

variables:
  PNPM_STORE_PATH: .pnpm-store

default:
  image: node:20
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-9 --activate
    - pnpm config set store-dir $PNPM_STORE_PATH
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - $PNPM_STORE_PATH

install:
  stage: install
  script:
    - pnpm install
  artifacts:
    paths:
      - node_modules/
      - pnpm-lock.yaml
      - .pnpm-store
  rules:
    - if: '$CI_COMMIT_BRANCH'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

build:
  stage: build
  script:
    - pnpm run build
  needs:
    - job: install
      artifacts: true
  artifacts:
    paths:
      - dist/
  rules:
    - if: '$CI_COMMIT_BRANCH'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

prettier:
  stage: quality
  script:
    - pnpm run prettier:check # Запуск Prettier для проверки форматирования
  dependencies:
    - install # Получаем артефакты с этапа install

eslint:
  stage: quality
  script:
    - pnpm run lint:check # Запуск ESLint для анализа кода
  dependencies:
    - install # Получаем артефакты с этапа install

test:
  stage: quality
  script:
    - pnpm run test # Запуск тестов с помощью Vitest
  dependencies:
    - install # Получаем артефакты с этапа install

types:
  stage: quality
  script:
    - pnpm run types:check # Запуск проверки типов TypeScript
  dependencies:
    - install # Получаем артефакты с этапа install

pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp -r dist/* public/
  needs:
    - job: build
      artifacts: true
  artifacts:
    paths:
      - public
  environment:
    name: $CI_ENVIRONMENT_NAME
    url: https://$CI_PROJECT_NAMESPACE.gitlab.io/$CI_PROJECT_NAME/$CI_COMMIT_REF_SLUG
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      variables:
        CI_ENVIRONMENT_NAME: production

    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      variables:
        CI_ENVIRONMENT_NAME: review/$CI_COMMIT_REF_SLUG