build:
  stage: build
  script:
    - pnpm run build
  dependencies:
    - install
  artifacts:
    paths:
      - dist/
    reports:
      dotenv: build.env  # Сохраняем информацию о сборке
    expire_in: 1 week

review:
  stage: deploy
  script:
    - mkdir -p public
    - cp -r dist/* public/
  dependencies:
    - build
  needs:
    - job: build
      artifacts: true  # Явно запрашиваем артефакты
  artifacts:
    paths:
      - public
  only:
    - merge_requests